### ISSUE TITLE
Dumps do not work

### ISSUE THREAD

**Issue by danohuiginn** [parltrack/parltrack#12]
The dumps at http://parltrack.euwiki.org/dumps/ aren't useable for creating a parltrack installation.

1) The dumps were seemingly built using --jsonArray. Mongo can only re-import this format with files under 16MB; parltrack dumps are much larger

I ended up using a roundabout way -- writing a python script to break the jsonArray into chunks, and then importing them individually. 
The file is https://gist.github.com/danohuiginn/8649383, used like this:

curl http://parltrack.euwiki.org/dumps/eurlex.json.xz | xz -dc | ./splitjson.py eurlex
for i in `ls eurlex*json` ; do cat $i | mongoimport -d parltrack -c eurlex --jsonArray; done

2) the json dumps mangle dates -- they end up as strings in mongo, not date objects. This messes up a lot of the code.

I think the correct solution would be to provide dumps in one of these ways:
a) do a straight mongo dump to somewhere public
b) allow master-slave replication of stef's db. This would also allow for regular propagation of updates

**Comment by stef** [comment]
actually we are able to load all dumps at once in memory. stay tuned for v2.0 to see how it works (or you can peek in the pt2 branch already) the dumps will have a format that lends itself to sax-style reading, one record/line.
