### ISSUE TITLE
Parsing on the declaration of interests get confused with events

### ISSUE THREAD

**Issue by tttp** [parltrack/parltrack#20]
Hi,
On the tab, you have both pdfs for the declarations of interest and "Declarations of participation by Members in events organised by third parties" 

@asciimoo You should only parse the first bloc (declaration of interest) and ignore the second (events), otherwise you have empty "declarations"

http://www.europarl.europa.eu/meps/en/96920/KAY_SWINBURNE_declarations.html

**Comment by stef** [comment]
fixed in new scraper.
