### ISSUE TITLE
Bogus(?) MEP data causes 500 error on parltrack

### ISSUE THREAD

**Issue by tomjorquera** [parltrack/parltrack#28]
Hi,

I noticed an issue when trying to access information related to the MEP named "Maurizio Enzo LUPI" on the parltrack instance at http://parltrack.euwiki.org/.

When trying to search for "lupi", or accessing his page at http://parltrack.euwiki.org/mep/Maurizio%20Enzo%20LUPI, the server returns a 500 error.

I discovered the issue investigating another issue with another project using the raw JSON data provided on http://parltrack.euwiki.org/. In the other project, the json import was crashing on this very same MEP due to the fact that **the data for this MEP does not contains a birthdate**. Maybe it is related ?

Below is the parltrack json entry for this MEP (beautified for convenience):

```
{
    "Name": {
        "familylc": "lupi",
        "full": "Maurizio Enzo LUPI",
        "sur": "Maurizio Enzo",
        "family": "LUPI",
        "aliases": [
            "LUPI Maurizio Enzo",
            "lupi maurizio enzo",
            "lupi",
            "maurizioenzolupi",
            "MaurizioEnzoLUPI",
            "maurizio enzo lupi",
            "LUPIMaurizioEnzo",
            "lupimaurizioenzo",
            "LUPI",
            "Maurizio Enzo LUPI"
        ]
    },
    "Photo": "http://www.europarl.europa.eu/mepphoto/124782.jpg",
    "UserID": 124782,
    "active": false,
    "meta": {
        "url": "http://www.europarl.europa.eu/meps/en/124782/_history.html",
        "created": "2014-07-01T16:08:56"
    },
    "Constituencies": [
        {
            "party": "Nuovo Centrodestra - Unione di Centro",
            "country": "Italy",
            "end": "2014-07-02T00:00:00",
            "start": "2014-07-01T00:00:00"
        },
        null
    ],
    "Mail": [
        "maurizioenzo.lupi@europarl.europa.eu"
    ],
    "_id": "53b2dd18b819f205b00000b7",
    "changes": {
        "2014-07-01T16:08:56": [
            {
                "type": "added",
                "data": {
                    "familylc": "lupi",
                    "full": "Maurizio Enzo LUPI",
                    "sur": "Maurizio Enzo",
                    "family": "LUPI",
                    "aliases": [
                        "LUPI Maurizio Enzo",
                        "lupi maurizio enzo",
                        "lupi",
                        "maurizioenzolupi",
                        "MaurizioEnzoLUPI",
                        "maurizio enzo lupi",
                        "LUPIMaurizioEnzo",
                        "lupimaurizioenzo",
                        "LUPI",
                        "Maurizio Enzo LUPI"
                    ]
                },
                "path": [
                    "Name"
                ]
            },
            {
                "type": "added",
                "data": "http://www.europarl.europa.eu/mepphoto/124782.jpg",
                "path": [
                    "Photo"
                ]
            },
            {
                "type": "added",
                "data": 124782,
                "path": [
                    "UserID"
                ]
            },
            {
                "type": "added",
                "data": [
                    {
                        "party": "Nuovo Centrodestra - Unione di Centro",
                        "country": "Italy",
                        "end": "9999-12-31T00:00:00",
                        "start": "2014-07-01T00:00:00"
                    }
                ],
                "path": [
                    "Constituencies"
                ]
            },
            {
                "type": "added",
                "data": true,
                "path": [
                    "active"
                ]
            },
            {
                "type": "added",
                "data": [
                    "maurizioenzo.lupi@europarl.europa.eu"
                ],
                "path": [
                    "Mail"
                ]
            },
            {
                "type": "added",
                "data": [],
                "path": [
                    "CV"
                ]
            }
        ]
    },
    "CV": []
}

```

**Comment by stef** [comment]
hey Tom,

thanks very much for contacting me about this. i appreciate all such feedback!

On Thu, Jan 12, 2017 at 03:52:55AM -0800, Tom Jorquera wrote:
> When trying to search for "lupi", or accessing his page at http://parltrack.euwiki.org/mep/Maurizio%20Enzo%20LUPI, the server returns a 500 error.
> Below is the parltrack json entry for this MEP (beautified for convenience):

thanks! makes things much easier.

>     "Constituencies": [
>         {
>             "party": "Nuovo Centrodestra - Unione di Centro",
>             "country": "Italy",
>             "end": "2014-07-02T00:00:00",
>             "start": "2014-07-01T00:00:00"
>         },

this is the problem, the guy was only one day in office, at the very start of
the period. why? i dunno, maybe he changed his mind or fell out of favour. but
it was only enough to make a rudimentary record but there was never any
data supplied by him. if you look at the EP meps website you'll also not find
him. so maybe this was a mistake. for historic reasons though, i like to keep
this guy in the db. but i'll have to fix the 500 on the website.

what do you think?

s

**Comment by tomjorquera** [comment]
No problem, thanks for working on this great project!

Do you have an idea of the actual reason this data entry is causing the error? Obviously knowing what exactly is causing the issue would help quite a bit in deciding how to fix it 😄

I am not too familiar with the codebase to say the least ^^, but by looking at a few places it seems to take in account the case where the birthdate is not present. So I am not too much convinced by my first guess in this reguard.

On my side, I am fiddling with the codebase to setup a local instance and reproduce the issue (never as easy at it seems).

On a side-note, [I found more info about our guy](https://en.wikipedia.org/wiki/Maurizio_Lupi), so I guess trying hot-fixing the data could be a possibility if the issue is too hard to tackle.

As a remark, I understand your desire to keep a track of such data. But be careful, since the info is not available anymore on the source, it means that your current database cannot be rebuilt from scratch! So be careful about your backups 😉

**Comment by stef** [comment]
On Thu, Jan 12, 2017 at 01:54:24PM -0800, Tom Jorquera wrote:
> No problem, thanks for working on this great project!
> 
> Do you have an idea of the actual reason this data entry is causing the error? Obviously knowing what exactly is causing the issue would help quite a bit in deciding how to fix it 😄

probably a lot of data is missing that is assumed to exist.

> I am not too familiar with the codebase to say the least ^^, but by looking at a few places it seems to take in account the case where the birthdate is not present. So I am not too much convinced by my first guess in this reguard.
> 
> On my side, I am fiddling with the codebase to setup a local instance and reproduce the issue (never as easy at it seems).

i guess i have to fix it in my view controllers.

> As a remark, I understand your desire to keep a track of such data. But be careful, since the info is not available anymore on the source, it means that your current database cannot be rebuilt from scratch! So be careful about your backups 😉

heh, thanks for the hint, i have other data that is unique and cannot be
recovered. ;)

**Comment by stef** [comment]
for historical reasons i would  like to not touch this record in the db. every user of parltrack has to decide themselves, how to handle this, as the source i have to provide all data, the users can then decide themselves what to use or what to discard.

if you agree, i close this issue.

**Comment by tomjorquera** [comment]
@stef, your choice is understandable.

You may still want to fix the issue with the error 500 being thrown when trying to access the data on the website 😄
Keeping the issue open to keep track of this error could make sense, but it's your call of course.

Despite what I have said, I sadly did not have time to investigate the issue on my own (as it is often the case). I may still try to investigate it at some point in the future, but I can't promise anything...
