### ISSUE TITLE
ep_amendments.json - No updates since 2020-02-28

### ISSUE THREAD

**Issue by gautiermorel** [parltrack/parltrack#44]
Hello !
First, thanks a lot for you great work !

I realised that amendments are not synced since 2020-02-28, is that something we can do to put it back ?

Thanks,

**Comment by stef** [comment]
oh? shit. i didn't notice. will have a look and try to fix it. was there many amendments since covid19 struck?

**Comment by gautiermorel** [comment]
Thanks ! Yes i think so cause at least 4 plenary sessions took place in the meantime ! If i can help, let me know :)

**Comment by stef** [comment]
it seems the EP changed their website again... i need to update the scraper...

**Comment by stef** [comment]
d426e78b895411819c7a39cf7fc94c97885e78a1 should fix this.

**Comment by stef** [comment]
if you agree, please close this issue as a confirmation.

**Comment by gautiermorel** [comment]
awesome ! Thanks a lot !
