### ISSUE TITLE
Name (Full, sur, family) missing

### ISSUE THREAD

**Issue by gautiermorel** [parltrack/parltrack#45]
Hi,

I noticed that there is no more "name" fields on the files for some MEPs (only aliases).
<img width="874" alt="Screenshot 2021-01-26 at 12 16 07" src="https://user-images.githubusercontent.com/5614250/105838567-89858f80-5fd0-11eb-8ae6-8676f00c36ac.png">

How can I help?

Thanks again for all your work !
Gautier

**Comment by stef** [comment]
interesting. haven't noticed this so far. but currently we have a bigger problem (see the website) as soon as that is solved, i'll have a look at this issue.
