### ISSUE TITLE
ep_votes.json - No updates since 2020-11-30

### ISSUE THREAD

**Issue by gautiermorel** [parltrack/parltrack#46]
Hello ! Sorry I come back to you again ! I hope that you finally managed to solve the big issue on Parltrack !
Also, I realised that `ep_votes` is not updated since 2020-11-30 !

Can I help with something ?

Regards,

**Comment by stef** [comment]
oh. thank you are already massively helping with reporting these kind of issues!
it seems the EP website does not allow to search for roll-call vote in the minutes section. this is either a bug, or a change in the website. gotta have a look. thanks again for reporting!

**Comment by gautiermorel** [comment]
Seems like the new urls for Roll-calls is: 
`https://www.europarl.europa.eu/doceo/document/PV-X-XXXX-XX-XX-RCV_FR.xml`
From your scraper:
`http://www.europarl.europa.eu/RegData/seance_pleniere/proces_verbal/%s/votes_nominaux/xml/P%s_PV%s(RCV)_XC.xml`

And also, when I tried in EN, i was redirected to the FR xml ... Can be a lead also !

Feel free to come back to me for any help !
Good evening !

**Comment by stef** [comment]
i just contacted the EP witht he followin report:

> Dear EP Webmistresses and Webmasters,
> 
> I was looking for the 2020 Plenary Roll-call Votes. and went here:
> 
> https://www.europarl.europa.eu/plenary/en/votes.html?tab=votes
> 
> which gives me a beautiful summary of the latest plenaries and their votes. I searched using the form found on:
> 
> https://www.europarl.europa.eu/plenary/en/minutes.html
> 
> I added the dates 2020/01/01 - 2020/12/31, and I set the "In title" radio button, and entered as search text:
> "Roll-call votes"
> 
> I got zero results.
> 
> If I change from "in title" to "in text" I get 189 hits, which somewhere deep in the middle of it also contain the coveted roll-call votes documents.
> 
> I think your search function is broken.
> 
> thank you very much for your fine service.
> Best Regards,
> Stefan Marsiske

**Comment by gautiermorel** [comment]
Thanks for the update ! Looking forward to hearing from them !
Good evening !

**Comment by stef** [comment]
i manually added all missing rcvs, we'll see how the EP responds to the search issue, if they fix it, i'll adopt the crawler.

**Comment by gautiermorel** [comment]
Hello ! You told me that you did it manually but I still see that the `ep_votes.json.lz` on https://parltrack.org/dumps are still updated from 2020-11-30. Still no answer from the EP Webmasters ? Regards,

**Comment by stef** [comment]
oh, it might be that i have not dumped the database, but if you check the webinterface, you can find newer vote results. i'll dump the db, check it out.

**Comment by stef** [comment]
EP webmasters are quiet btw. i guess WFH is not so quick

**Comment by stef** [comment]
i got this answer:

> Thank you for your e-mail and for your interest in our activities. Please find below the explanation received from the team in charge:                                                                       
>                                                                                                                                                                                                              
> The form found on https://www.europarl.europa.eu/plenary/en/minutes.html searches in the Minutes of plenary sessions. When you select "in title", you are looking for the words in the title of each         
> individual point in the minutes. Since there are no points titled "Roll-call votes", the results are zero. When you select "in text", you are looking for the words in the text of each individual point. The
> results are 189 because in 189 "roll-call votes" is mentioned during the session. Example:                                                                                                                   
> [cid:image003.jpg@01D71400.106810D0]                                                                                                                                                                         
> Since what you are looking for is a document, we recommend using the EP Register of Documents website: https://www.europarl.europa.eu/RegistreWeb                                                            
> You can select document type "Finalised minutes" under Advanced Search form:                                                                                                                                 
> [cid:image004.jpg@01D71400.106810D0]                                                                                                                                                                         
>                                                                                                                                                                                                              
> The results include all minutes documents and their annexes (Voting results, Attendance list and Roll-call votes                                                                                             
> https://www.europarl.europa.eu/RegistreWeb/search/simpleSearchHome.htm?typesDoc=PPVD&searchLanguages=EN&sortAndOrder=DATE_DOCU_DESC

apparently this changed recently, before this change i was able to find all Roll-call votes using this interface. i'll adapt my crawler accordingly.

**Comment by stef** [comment]
i must say i'm impressed the EP created a search interface that accepts json and spits out quite detailed metadata json. it seems to come from solr. anyway, the plenary votes crawler and scraper are adapted to this and running reliably, https://github.com/parltrack/parltrack/commit/ddc139a0bf804de93b5b87b29d0aad7e4076da8f please close this issue if you agree that everything is dandy.
thanks for reporting!

**Comment by gautiermorel** [comment]
awesome !
