### ISSUE TITLE
Committee `associated` incorrect for some dossiers

### ISSUE THREAD

**Issue by ghxm** [parltrack/parltrack#50]
Similar to #49 

When randomly checking the data in the `ep_dosiers.json`  data dump (2022-05-22), I noticed that the `associated` information for the AGRI committee in https://oeil.secure.europarl.europa.eu/oeil//popups/ficheprocedure.do?reference=2013/0137(COD)&l=en seems to be wrong.

Again (#49), when running the dossier scraper manually, the information is reflected correctly in the resulting dictionary.

**Comment by stef** [comment]
what exactly is wrong with this

>  associated information for the agri committe

what do you have? what do you expect?

**Comment by ghxm** [comment]
Sorry, I should have been more clear. Thanks for getting back!

For the given procedure the AGRI committee is listed as an associated committee (`associated: True`). As I understand and as it is reflected when re-running the scraping function on this procedure, this should be `False` as AGRI the responsible committee.
