### ISSUE TITLE
No current MEPs exist since 2024 election

### ISSUE THREAD

**Issue by handelaar** [parltrack/parltrack#53]
Seems from the logs that the list of MEPs excludes everyone elected last month

**Comment by handelaar** [comment]
I'm hoping that #54 will help

**Comment by stef** [comment]
hey, only partly,but https://github.com/parltrack/parltrack/commit/a77b055fa5695b936ef1e5052e99049e02f3b8d4 seems to fix the problem. i tested it with a returning and a newbie mep. will hopefully be in tomorrows dump updated.

thank you for reporting and attempting to fix! i expect more issues with a 2 digit term in other scrapers, exciting times...

<3 for everything!
