### ISSUE TITLE
missing keys in meps json

### ISSUE THREAD

**Issue by Ante-Wessels** [parltrack/parltrack#55]
While looking for committees I got key errors for abbr in the meps json:

missing abbr key, id: 124701 org: Subcommittee on Tax Matters
missing abbr key, id: 197697 org: Subcommittee on Tax Matters
missing abbr key, id: 256878 org: Subcommittee on Public Health
missing abbr key, id: 256842 org: Subcommittee on Public Health
missing abbr key, id: 256864 org: Subcommittee on Public Health
missing abbr key, id: 257010 org: Subcommittee on Tax Matters
missing abbr key, id: 257112 org: Subcommittee on Public Health

Subcommittee on Tax Matters is FISC

Subcommittee on Tax Matters
https://www.europarl.europa.eu/committees/en/fisc/home/highlights

Subcommittee on Public Health
SANT

https://www.europarl.europa.eu/committees/en/sant/home/highlights

Both not in mappings 
https://github.com/parltrack/parltrack/blob/master/utils/mappings.py

--------

There is also an other key missing:

KeyError: 'Constituencies'. 

This may be related to the following. 

Two MEPs do not have a Country value: Alicia HOMS GINEL and Martin HLAVÁČEK. 

The EP website mentions their country. Parltrack mentions them too, in the overview page:

https://parltrack.eu/meps

But not on the MEP page. 

https://parltrack.eu/mep/122978/Alicia%20HOMS%20GINEL

Homs has no current constituencies, only earlier ones.

good luck, thanks

Ante

**Comment by stef** [comment]
hey, thanks for reporting and excuses for the delayed response! the mappings have been updated. however the lack of constituencies for the two meps is not trivial for us to fix. i will contact someone in the EP to try to fix this internally.

**Comment by stef** [comment]
for the fix, see: https://github.com/parltrack/parltrack/commit/aa7c1aa16b6282b437ee62c6b535802b95511534

**Comment by stef** [comment]
if you agree this fixes your problem, please close this issue.

**Comment by Ante-Wessels** [comment]
Thanks!
