### ISSUE TITLE
missing delegations abbrevations

### ISSUE THREAD

**Issue by Ante-Wessels** [parltrack/parltrack#56]
Hi, there are some delegation abbreviations missing in the meps json (term 10, may be earlier).

I do not find them in

https://github.com/parltrack/parltrack/blob/master/utils/mappings.py .

The mapping has:

Members from the European Parliament to the Joint Parliamentary Assembly of the Agreement between the African, Caribbean and Pacific States and the European Union (ACP-EU)": "DACP",

and:

"Members from the European Parliament to the Joint Assembly of the Agreement between the African, Caribbean and Pacific States and the European Union (ACP-EU)": u"",

but not:
DPAC: Delegation to the Pacific-EU Parliamentary Assembly

I do find DEEA in mappings.py:

Delegation for relations with Switzerland and Norway and to the EU-Iceland Joint Parliamentary Committee and the European Economic Area (EEA) Joint Parliamentary Committee

Delegation for relations with Switzerland, Iceland and Norway and to the European Economic Area (EEA) Joint Parliamentary Committee

Switzerland, Iceland and Norway and European Economic Area (EEA)

Switzerland, Norway and the EU-Iceland and EEA JPCs

However, term10 uses:

Delegation for Northern cooperation and for relations with Switzerland and Norway and to the EU-Iceland Joint Parliamentary Committee and the European Economic Area (EEA) Joint Parliamentary Committee

So it seems Parliament renamed some delegations.

Here is the list:

"Delegation for Northern cooperation and for relations with Switzerland and Norway and to the EU-Iceland Joint Parliamentary Committee and the European Economic Area (EEA) Joint Parliamentary Committee": "DEEA"
 "Delegation for relations with Bosnia and Herzegovina and Kosovo, including the EU-Bosnia and Herzegovina Stabilisation and Association Parliamentary Committee and the EU-Kosovo Stabilisation and Association Parliamentary Committee": "DSEE"
"Delegation for relations with Central Asia": "DCAS"
"Delegation for relations with Iraq, including the EU-Iraq Parliamentary Cooperation Committee": "D-IQ"
"Delegation for relations with the countries of Central America, including the EU-Central America Parliamentary Association Committee": "DCAM"
"Delegation for relations with the Maghreb countries and the Arab Maghreb Union, including the EU-Morocco, EU-Tunisia andEU-Algeria Joint Parliamentary Committees": "DMAG"
"Delegation to the Africa-EU Parliamentary Assembly": "DAFR"
"Delegation to the Caribbean-EU Parliamentary Assembly": "DCAB"
"Delegation to the EU-Armenia Parliamentary Partnership Committee, the EU-Azerbaijan Parliamentary Cooperation Committee and the EU-Georgia Parliamentary Association Committee": "DSCA"
"Delegation to the EU-North Macedonia Joint Parliamentary Committee": "D-MK"
"Delegation to the EU-Türkiye Joint Parliamentary Committee": "D-TR"
"Delegation to the EU-UK Parliamentary Partnership Assembly": "D-UK"
"Delegation to the OACPS-EU Joint Parliamentary Assembly": "OACPS"
"Delegation to the Pacific-EU Parliamentary Assembly": "DPAC"

links:
https://www.europarl.europa.eu/delegations/en/DEEA
https://www.europarl.europa.eu/delegations/en/DSEE
https://www.europarl.europa.eu/delegations/en/DCAS
https://www.europarl.europa.eu/delegations/en/D-IQ
https://www.europarl.europa.eu/delegations/en/DCAM
https://www.europarl.europa.eu/delegations/en/DMAG
https://www.europarl.europa.eu/delegations/en/DAFR
https://www.europarl.europa.eu/delegations/en/DCAB
https://www.europarl.europa.eu/delegations/en/DSCA
https://www.europarl.europa.eu/delegations/en/D-MK
https://www.europarl.europa.eu/delegations/en/D-TR
https://www.europarl.europa.eu/delegations/en/D-UK
https://www.europarl.europa.eu/delegations/en/DPAC
https://www.europarl.europa.eu/oacps/en/home

kind regards, thanks,

Ante

**Comment by Ante-Wessels** [comment]
missing space: andEU-Algeria (DMAG)

**Comment by stef** [comment]
<3 <3 <3

**Comment by Ante-Wessels** [comment]
Dear Stef,

Unfortunately, the new delegations still do not get an abbreviation in the ep_meps.json.lz

For instance:

Delegation to the Africa-EU Parliamentary Assembly

is now part of 
https://github.com/parltrack/parltrack/blob/master/utils/mappings.py

with "DAFR" as abbreviation. 

However, the json has:

      {
        "role": "Member",
        "Organization": "Delegation to the Africa-EU Parliamentary Assembly",
        "start": "2024-09-19T00:00:00",
        "end": "9999-12-31T00:00:00",
        "term": 10
      },

I do not see what could be going wrong.

kind regards,

Ante

**Comment by stef** [comment]
the scrapers haven't been restarted, they were last restarted on the 22nd of september. will restart them asap.

**Comment by Ante-Wessels** [comment]
Ah, that's it, thanks!
