### ISSUE TITLE
A new delegation name:

### ISSUE THREAD

**Issue by Ante-Wessels** [parltrack/parltrack#57]
Hi,

There is already a new delegation name:

"Delegation for relations with the countries of Central America, including the EU-Central America Association Parliamentary Committee": "DCAM",

not yet in 

https://github.com/parltrack/parltrack/blob/master/utils/mappings.py

kind regards,

Ante

**Comment by stef** [comment]
should be fixed by https://github.com/parltrack/parltrack/commit/df90122e7da9e99ec54c02cd8306af08b3b713cd
