### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Ante-Wessels** [parltrack/parltrack#58]
Hi, 

Just saw that Kateřina KONEČNÁ has telegram:

https://www.europarl.europa.eu/meps/en/23699/KATERINA_KONECNA/home

not yet spotted by Parltrack:
https://parltrack.org/mep/23699/Kate%C5%99ina%20KONE%C4%8CN%C3%81#/contact

kind regards,

Ante

**Comment by stef** [comment]
should be fixed by https://github.com/parltrack/parltrack/commit/8caf09437fc3b1143e48f58d0496ece8105bda9e

**Comment by Ante-Wessels** [comment]
Thanks!
