### ISSUE TITLE
Blog social media

### ISSUE THREAD

**Issue by Ante-Wessels** [parltrack/parltrack#59]
Dear Stef, 

I found MEPs which have the social media "Blog", for instance:

https://www.europarl.europa.eu/meps/en/96791/ELZBIETA+KATARZYNA_LUKACIJEWSKA/home

to find them I used this in a scraper (with the rest of the scraper code earlier on):
        
        search_media = True
        if search_media:
            for i in ["TikTok", "WeChat", "Snapchat", "Reddit", "Pinterest", "Quora", "Teams", "Skype", "Threads", "Twitch", "Discord", "Tumblr", "Bluesky", "Mastodon", "Blog",]:
                search_path = f"//a[@data-original-title='{i}']/@href"
                s_list = tree.xpath(search_path)
                if s_list:
                    print(name_from_title_tag, s_list)
        

Funny thing is, I found "Blog" in very old code, so I wondered whether some MEPs still used it. 

Should the list be longer?

have a nice evening!

Ante

**Comment by stef** [comment]
sorry for the late answer,  i was swamped the last weeks. thank you for the interesting issue. i added blog, to the fixed list of personal links. and i added a warning if any kind of link is listed that is not one of 

```
'Website', 'E-mail', 'Facebook', 'Facebook', 'Youtube', 'Blog', 'X', 'Instagram', 'Telegram'
```
in that case the scraper throws a warning, and we can see all of them at https://parltrack.org/log/2024-10-31

**Comment by Ante-Wessels** [comment]
Yes, that is a better approach. I only found the ones I was looking for, you find the unknown unknowns. I saw you added LinkedIn. 

Thanks!
